const authStyles = {
  page: {
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
    padding: '24px',
    backgroundColor: '#f5f6fa',
  },
  centered: {
    minHeight: '100vh',
    display: 'grid',
    placeItems: 'center',
  },
  form: {
    width: '100%',
    maxWidth: '420px',
    display: 'flex',
    flexDirection: 'column',
    padding: '32px',
    borderRadius: '14px',
    backgroundColor: '#fff',
    boxShadow: '0 12px 32px rgba(17, 24, 39, 0.12)',
  },
  logo: { width: '88px', height: '88px', alignSelf: 'center' },
  title: { margin: '0 0 24px', textAlign: 'center', color: '#111827' },
  label: { margin: '14px 0 6px', fontWeight: 600, color: '#374151' },
  input: {
    width: '100%',
    padding: '11px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    fontSize: '1rem',
  },
  remember: { display: 'flex', gap: '8px', margin: '18px 0', color: '#4b5563' },
  button: {
    padding: '12px 18px',
    border: 0,
    borderRadius: '8px',
    backgroundColor: '#4b5563',
    color: '#fff',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  alert: {
    padding: '10px 12px',
    borderRadius: '8px',
    backgroundColor: '#fee2e2',
    color: '#991b1b',
  },
  error: { marginTop: '5px', color: '#b91c1c', fontSize: '0.875rem' },
  switchForm: { margin: '20px 0 0', textAlign: 'center', color: '#6b7280' },
  link: { color: '#374151', fontWeight: 600 },
};

export default authStyles;
